package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * Ratings generated by hbm2java
 */
@Entity
@Table(name = "ratings", schema = "public")
public class Rating implements java.io.Serializable {

    @Id
    @Column(name = "movieid")
    private Integer movieid;

    @Column(name = "rank", nullable = false, length = 4)
    private String rank;

    @Column(name = "votes")
    private Integer votes;

    @Column(name = "distribution", nullable = false, length = 10)
    private String distribution;

    public Rating() {
    }

    public String getRank() {
        return rank;
    }

    public void setRank(String rank) {
        this.rank = rank;
    }

    public Integer getVotes() {
        return votes;
    }

    public void setVotes(Integer votes) {
        this.votes = votes;
    }

    public String getDistribution() {
        return distribution;
    }

    public void setDistribution(String distribution) {
        this.distribution = distribution;
    }
}
